### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by yosaf12345** [arysoftplay/-rySubRipper#2]
[
[run.log](https://github.com/arysoftplay/-rySubRipper/files/8222763/run.log)
](url)

**Comment by yosaf12345** [comment]
ERROR: Parameter background_mode missing on the database

**Comment by arysoftplay** [comment]
Hi Yosaf,
You are right. There was a parameter missing in the database. 
Just fixed it.
You can download again default_ocr.db and res/_ocr.db or the full release 1.4.
